name: Environment Modules
website_url: https://cea-hpc.github.io/modules/
description: Environment Modules provides for the dynamic modification of a user's environment via modulefiles.
licenses:
  - GPL-2.0
platforms:
  - Tcl
tags:
  - Build and software organization tools
source_code_url: https://github.com/cea-hpc/modules
stargazers_count: 608
updated_at: '2023-11-27'
archived: false
