on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make awesome_lint
      - run: make export
